version: '3.7'

services:
  nginx:
    image: openresty/openresty
    container_name: openresty
    volumes:
      - ./openresty/nignx.conf:/etc/nginx/nginx.conf
      - ./openresty/conf.d:/etc/nginx/conf.d
    expose:
      - 80
    networks:
      server_network_net:
        ipv4_address: 10.0.1.11

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    command: "true"

networks:
  server_network_net:
    driver: bridge
    name: server_network
    ipam:
      config:
        - subnet: 10.0.1.0/24